name: Size

on:
  pull_request:

jobs:
  size:
    name: Size
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - uses: andresz1/size-limit-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
